#ifndef HW_TI_LP_MSP_EXP430G2_H
#define HW_TI_LP_MSP_EXP430G2_H

#define HW_INDICATOR_1_SEL P1SEL
#define HW_INDICATOR_1_SEL2 P1SEL2
#define HW_INDICATOR_1_DIR P1DIR
#define HW_INDICATOR_1_OUT P1OUT
#define HW_INDICATOR_1_PIN BIT0

#define HW_INDICATOR_2_SEL P1SEL
#define HW_INDICATOR_2_SEL2 P1SEL2
#define HW_INDICATOR_2_DIR P1DIR
#define HW_INDICATOR_2_OUT P1OUT
#define HW_INDICATOR_2_PIN BIT6

#define HW_BUTTON_2_SEL P1SEL
#define HW_BUTTON_2_SEL2 P1SEL2
#define HW_BUTTON_2_DIR P1DIR
#define HW_BUTTON_2_REN P1REN
#define HW_BUTTON_2_OUT P1OUT
#define HW_BUTTON_2_PIN BIT3

#endif /* HW_TI_LP_MSP_EXP430G2_H */
