#ifndef HW_TI_LP_MSP_EXP430G2_H
#define HW_TI_LP_MSP_EXP430G2_H

#define HW_INDICATOR_1_PORT 1
#define HW_INDICATOR_1_PIN 0

#define HW_INDICATOR_2_PORT 1
#define HW_INDICATOR_2_PIN 6

#define HW_BUTTON_2_PORT 1
#define HW_BUTTON_2_PIN 3

#endif /* HW_TI_LP_MSP_EXP430G2_H */
